// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package dbgen

import (
	"context"
)

const addStoryLabel = `-- name: AddStoryLabel :exec
INSERT INTO story_labels (story_id, label_id) VALUES (?1, ?2)
`

type AddStoryLabelParams struct {
	StoryID int64
	LabelID int64
}

func (q *Queries) AddStoryLabel(ctx context.Context, arg AddStoryLabelParams) error {
	_, err := q.db.ExecContext(ctx, addStoryLabel, arg.StoryID, arg.LabelID)
	return err
}

const clearStoryLabels = `-- name: ClearStoryLabels :exec
DELETE FROM story_labels WHERE story_id = ?1
`

func (q *Queries) ClearStoryLabels(ctx context.Context, storyID int64) error {
	_, err := q.db.ExecContext(ctx, clearStoryLabels, storyID)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (project_id, name) VALUES (?1, ?2)
RETURNING id, project_id, name
`

type CreateLabelParams struct {
	ProjectID int64
	Name      string
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel, arg.ProjectID, arg.Name)
	var i Label
	err := row.Scan(&i.ID, &i.ProjectID, &i.Name)
	return i, err
}

const deleteUnusedLabels = `-- name: DeleteUnusedLabels :exec
DELETE FROM labels
WHERE labels.project_id = ?1
  AND NOT EXISTS (SELECT 1 FROM story_labels WHERE story_labels.label_id = labels.id)
`

func (q *Queries) DeleteUnusedLabels(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUnusedLabels, projectID)
	return err
}

const getLabelByName = `-- name: GetLabelByName :one
SELECT id, project_id, name FROM labels WHERE project_id = ?1 AND name = ?2
`

type GetLabelByNameParams struct {
	ProjectID int64
	Name      string
}

func (q *Queries) GetLabelByName(ctx context.Context, arg GetLabelByNameParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByName, arg.ProjectID, arg.Name)
	var i Label
	err := row.Scan(&i.ID, &i.ProjectID, &i.Name)
	return i, err
}

const listLabels = `-- name: ListLabels :many
SELECT id, project_id, name FROM labels WHERE project_id = ?1 ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, projectID int64) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectStoryLabels = `-- name: ListProjectStoryLabels :many
SELECT story_labels.story_id, labels.name
FROM story_labels
JOIN labels ON labels.id = story_labels.label_id
WHERE labels.project_id = ?1
ORDER BY labels.name
`

type ListProjectStoryLabelsRow struct {
	StoryID int64
	Name    string
}

func (q *Queries) ListProjectStoryLabels(ctx context.Context, projectID int64) ([]ListProjectStoryLabelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectStoryLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectStoryLabelsRow{}
	for rows.Next() {
		var i ListProjectStoryLabelsRow
		if err := rows.Scan(&i.StoryID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoryLabels = `-- name: ListStoryLabels :many
SELECT labels.name
FROM story_labels
JOIN labels ON labels.id = story_labels.label_id
WHERE story_labels.story_id = ?1
ORDER BY labels.name
`

func (q *Queries) ListStoryLabels(ctx context.Context, storyID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStoryLabels, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
