// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addStoryLabel = `-- name: AddStoryLabel :exec
INSERT INTO story_labels (story_id, label_id) VALUES (?1, ?2)
`

type AddStoryLabelParams struct {
	StoryID int64
	LabelID int64
}

func (q *Queries) AddStoryLabel(ctx context.Context, arg AddStoryLabelParams) error {
	_, err := q.db.ExecContext(ctx, addStoryLabel, arg.StoryID, arg.LabelID)
	return err
}

const clearStoryLabels = `-- name: ClearStoryLabels :exec
DELETE FROM story_labels WHERE story_id = ?1
`

func (q *Queries) ClearStoryLabels(ctx context.Context, storyID int64) error {
	_, err := q.db.ExecContext(ctx, clearStoryLabels, storyID)
	return err
}

const createEpic = `-- name: CreateEpic :one
INSERT INTO labels (project_id, name, description, is_epic)
VALUES (?1, ?2, ?3, TRUE)
RETURNING id, project_id, name, is_epic, description
`

type CreateEpicParams struct {
	ProjectID   int64
	Name        string
	Description string
}

func (q *Queries) CreateEpic(ctx context.Context, arg CreateEpicParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createEpic, arg.ProjectID, arg.Name, arg.Description)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsEpic,
		&i.Description,
	)
	return i, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (project_id, name) VALUES (?1, ?2)
RETURNING id, project_id, name, is_epic, description
`

type CreateLabelParams struct {
	ProjectID int64
	Name      string
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel, arg.ProjectID, arg.Name)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsEpic,
		&i.Description,
	)
	return i, err
}

const deleteUnusedLabels = `-- name: DeleteUnusedLabels :exec
DELETE FROM labels
WHERE labels.project_id = ?1
  AND NOT labels.is_epic
  AND NOT EXISTS (SELECT 1 FROM story_labels WHERE story_labels.label_id = labels.id)
`

// Plain labels disappear with their last story; epics are kept until demoted.
func (q *Queries) DeleteUnusedLabels(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUnusedLabels, projectID)
	return err
}

const getLabel = `-- name: GetLabel :one
SELECT id, project_id, name, is_epic, description FROM labels WHERE id = ?1
`

func (q *Queries) GetLabel(ctx context.Context, id int64) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabel, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsEpic,
		&i.Description,
	)
	return i, err
}

const getLabelByName = `-- name: GetLabelByName :one
SELECT id, project_id, name, is_epic, description FROM labels WHERE project_id = ?1 AND name = ?2
`

type GetLabelByNameParams struct {
	ProjectID int64
	Name      string
}

func (q *Queries) GetLabelByName(ctx context.Context, arg GetLabelByNameParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByName, arg.ProjectID, arg.Name)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsEpic,
		&i.Description,
	)
	return i, err
}

const listLabelStoryStats = `-- name: ListLabelStoryStats :many
SELECT story_labels.label_id, stories.type, stories.state, stories.estimate
FROM story_labels
JOIN stories ON stories.id = story_labels.story_id
JOIN labels ON labels.id = story_labels.label_id
WHERE labels.project_id = ?1 AND stories.deleted_at IS NULL
`

type ListLabelStoryStatsRow struct {
	LabelID  int64
	Type     string
	State    string
	Estimate sql.NullInt64
}

// Live stories per label with what progress needs.
func (q *Queries) ListLabelStoryStats(ctx context.Context, projectID int64) ([]ListLabelStoryStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLabelStoryStats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelStoryStatsRow{}
	for rows.Next() {
		var i ListLabelStoryStatsRow
		if err := rows.Scan(
			&i.LabelID,
			&i.Type,
			&i.State,
			&i.Estimate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
SELECT id, project_id, name, is_epic, description FROM labels WHERE project_id = ?1 ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, projectID int64) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IsEpic,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectStoryLabels = `-- name: ListProjectStoryLabels :many
SELECT story_labels.story_id, labels.name
FROM story_labels
JOIN labels ON labels.id = story_labels.label_id
WHERE labels.project_id = ?1
ORDER BY labels.name
`

type ListProjectStoryLabelsRow struct {
	StoryID int64
	Name    string
}

func (q *Queries) ListProjectStoryLabels(ctx context.Context, projectID int64) ([]ListProjectStoryLabelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectStoryLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectStoryLabelsRow{}
	for rows.Next() {
		var i ListProjectStoryLabelsRow
		if err := rows.Scan(&i.StoryID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoryLabels = `-- name: ListStoryLabels :many
SELECT labels.name
FROM story_labels
JOIN labels ON labels.id = story_labels.label_id
WHERE story_labels.story_id = ?1
ORDER BY labels.name
`

func (q *Queries) ListStoryLabels(ctx context.Context, storyID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStoryLabels, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels
SET name = ?1, description = ?2, is_epic = ?3
WHERE id = ?4
RETURNING id, project_id, name, is_epic, description
`

type UpdateLabelParams struct {
	Name        string
	Description string
	IsEpic      bool
	ID          int64
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, updateLabel,
		arg.Name,
		arg.Description,
		arg.IsEpic,
		arg.ID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsEpic,
		&i.Description,
	)
	return i, err
}
