// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Activity struct {
	ID        int64
	StoryID   int64
	UserID    int64
	Kind      string
	OldValue  string
	NewValue  string
	CreatedAt int64
}

type ApiToken struct {
	ID         int64
	UserID     int64
	Name       string
	TokenHash  string
	CreatedAt  int64
	LastUsedAt sql.NullInt64
	ExpiresAt  sql.NullInt64
}

type Comment struct {
	ID        int64
	StoryID   int64
	UserID    int64
	Body      string
	CreatedAt int64
	UpdatedAt int64
}

type Label struct {
	ID          int64
	ProjectID   int64
	Name        string
	IsEpic      bool
	Description string
}

type OauthClient struct {
	ID           int64
	ClientID     string
	Name         string
	RedirectUris string
	CreatedAt    int64
	LastUsedAt   sql.NullInt64
}

type OauthCode struct {
	ID            int64
	CodeHash      string
	UserID        int64
	ClientID      int64
	RedirectUri   string
	CodeChallenge string
	ExpiresAt     int64
	UsedAt        sql.NullInt64
	GrantID       sql.NullInt64
}

type OauthGrant struct {
	ID         int64
	UserID     int64
	ClientID   int64
	CreatedAt  int64
	LastUsedAt sql.NullInt64
}

type OauthToken struct {
	ID        int64
	GrantID   int64
	Kind      string
	TokenHash string
	ExpiresAt int64
	UsedAt    sql.NullInt64
}

type Project struct {
	ID                    int64
	Name                  string
	Description           string
	Slug                  string
	IterationLengthDays   int64
	IterationStartWeekday int64
	VelocityWindow        int64
	CreatedAt             int64
	UpdatedAt             int64
	ArchivedAt            sql.NullInt64
	EstimateBugsAndChores bool
	CombineIceboxBacklog  bool
}

type ProjectMember struct {
	ProjectID int64
	UserID    int64
	Role      string
}

type SavedFilter struct {
	ID        int64
	UserID    int64
	ProjectID int64
	Name      string
	Query     string
	CreatedAt int64
}

type Session struct {
	ID        int64
	TokenHash string
	UserID    int64
	CreatedAt int64
	ExpiresAt int64
}

type Story struct {
	ID          int64
	ProjectID   int64
	Title       string
	Description string
	Type        string
	State       string
	Estimate    sql.NullInt64
	Position    int64
	RequesterID int64
	OwnerID     sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
	AcceptedAt  sql.NullInt64
	DeletedAt   sql.NullInt64
}

type StoryBlocker struct {
	StoryID   int64
	BlockerID int64
}

type StoryLabel struct {
	StoryID int64
	LabelID int64
}

type Task struct {
	ID          int64
	StoryID     int64
	Description string
	Done        bool
	Position    int64
	CreatedAt   int64
	UpdatedAt   int64
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	DisplayName  string
	IsAdmin      bool
	CreatedAt    int64
	UpdatedAt    int64
	IsActive     bool
}
