// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Activity struct {
	ID        int64
	StoryID   int64
	UserID    int64
	Kind      string
	OldValue  string
	NewValue  string
	CreatedAt int64
}

type Comment struct {
	ID        int64
	StoryID   int64
	UserID    int64
	Body      string
	CreatedAt int64
	UpdatedAt int64
}

type Label struct {
	ID        int64
	ProjectID int64
	Name      string
}

type Project struct {
	ID                    int64
	Name                  string
	Description           string
	Slug                  string
	IterationLengthDays   int64
	IterationStartWeekday int64
	VelocityWindow        int64
	CreatedAt             int64
	UpdatedAt             int64
}

type Session struct {
	ID        int64
	TokenHash string
	UserID    int64
	CreatedAt int64
	ExpiresAt int64
}

type Story struct {
	ID          int64
	ProjectID   int64
	Title       string
	Description string
	Type        string
	State       string
	Estimate    sql.NullInt64
	Position    int64
	RequesterID int64
	OwnerID     sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
	AcceptedAt  sql.NullInt64
	DeletedAt   sql.NullInt64
}

type StoryLabel struct {
	StoryID int64
	LabelID int64
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	DisplayName  string
	IsAdmin      bool
	CreatedAt    int64
	UpdatedAt    int64
	IsActive     bool
}
