// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (client_id, name, redirect_uris, created_at)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, client_id, name, redirect_uris, created_at, last_used_at
`

type CreateOAuthClientParams struct {
	ClientID     string
	Name         string
	RedirectUris string
	CreatedAt    int64
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, createOAuthClient,
		arg.ClientID,
		arg.Name,
		arg.RedirectUris,
		arg.CreatedAt,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :exec
INSERT INTO oauth_codes (code_hash, user_id, client_id, redirect_uri, code_challenge, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateOAuthCodeParams struct {
	CodeHash      string
	UserID        int64
	ClientID      int64
	RedirectUri   string
	CodeChallenge string
	ExpiresAt     int64
}

func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthCode,
		arg.CodeHash,
		arg.UserID,
		arg.ClientID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthGrant = `-- name: CreateOAuthGrant :one
INSERT INTO oauth_grants (user_id, client_id, created_at)
VALUES (?1, ?2, ?3)
RETURNING id, user_id, client_id, created_at, last_used_at
`

type CreateOAuthGrantParams struct {
	UserID    int64
	ClientID  int64
	CreatedAt int64
}

func (q *Queries) CreateOAuthGrant(ctx context.Context, arg CreateOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRowContext(ctx, createOAuthGrant, arg.UserID, arg.ClientID, arg.CreatedAt)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createOAuthToken = `-- name: CreateOAuthToken :exec
INSERT INTO oauth_tokens (grant_id, kind, token_hash, expires_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreateOAuthTokenParams struct {
	GrantID   int64
	Kind      string
	TokenHash string
	ExpiresAt int64
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthToken,
		arg.GrantID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteEmptyOAuthGrants = `-- name: DeleteEmptyOAuthGrants :exec
DELETE FROM oauth_grants
WHERE NOT EXISTS (SELECT 1 FROM oauth_tokens WHERE oauth_tokens.grant_id = oauth_grants.id)
`

func (q *Queries) DeleteEmptyOAuthGrants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteEmptyOAuthGrants)
	return err
}

const deleteExpiredOAuthCodes = `-- name: DeleteExpiredOAuthCodes :exec
DELETE FROM oauth_codes WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredOAuthCodes(ctx context.Context, now int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOAuthCodes, now)
	return err
}

const deleteExpiredOAuthTokens = `-- name: DeleteExpiredOAuthTokens :exec
DELETE FROM oauth_tokens WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredOAuthTokens(ctx context.Context, now int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOAuthTokens, now)
	return err
}

const deleteIdleOAuthClients = `-- name: DeleteIdleOAuthClients :exec
DELETE FROM oauth_clients
WHERE COALESCE(oauth_clients.last_used_at, oauth_clients.created_at) <= ?1
  AND NOT EXISTS (SELECT 1 FROM oauth_grants WHERE oauth_grants.client_id = oauth_clients.id)
`

func (q *Queries) DeleteIdleOAuthClients(ctx context.Context, before sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteIdleOAuthClients, before)
	return err
}

const deleteOAuthGrant = `-- name: DeleteOAuthGrant :execrows
DELETE FROM oauth_grants WHERE id = ?1 AND user_id = ?2
`

type DeleteOAuthGrantParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteOAuthGrant(ctx context.Context, arg DeleteOAuthGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOAuthGrant, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOAuthGrantByID = `-- name: DeleteOAuthGrantByID :exec
DELETE FROM oauth_grants WHERE id = ?1
`

func (q *Queries) DeleteOAuthGrantByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthGrantByID, id)
	return err
}

const deleteUserOAuthGrants = `-- name: DeleteUserOAuthGrants :exec
DELETE FROM oauth_grants WHERE user_id = ?1
`

func (q *Queries) DeleteUserOAuthGrants(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserOAuthGrants, userID)
	return err
}

const getOAuthAccessTokenUser = `-- name: GetOAuthAccessTokenUser :one
SELECT oauth_grants.id AS grant_id, oauth_grants.last_used_at, users.id, users.email, users.password_hash, users.display_name, users.is_admin, users.created_at, users.updated_at, users.is_active, users.default_combine_icebox_backlog
FROM oauth_tokens
JOIN oauth_grants ON oauth_grants.id = oauth_tokens.grant_id
JOIN users ON users.id = oauth_grants.user_id
WHERE oauth_tokens.token_hash = ?1
  AND oauth_tokens.kind = 'access'
  AND oauth_tokens.expires_at > ?2
  AND users.is_active
`

type GetOAuthAccessTokenUserParams struct {
	TokenHash string
	Now       int64
}

type GetOAuthAccessTokenUserRow struct {
	GrantID    int64
	LastUsedAt sql.NullInt64
	User       User
}

func (q *Queries) GetOAuthAccessTokenUser(ctx context.Context, arg GetOAuthAccessTokenUserParams) (GetOAuthAccessTokenUserRow, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccessTokenUser, arg.TokenHash, arg.Now)
	var i GetOAuthAccessTokenUserRow
	err := row.Scan(
		&i.GrantID,
		&i.LastUsedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.DisplayName,
		&i.User.IsAdmin,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.IsActive,
		&i.User.DefaultCombineIceboxBacklog,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, client_id, name, redirect_uris, created_at, last_used_at FROM oauth_clients WHERE client_id = ?1
`

func (q *Queries) GetOAuthClient(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, getOAuthClient, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOAuthCode = `-- name: GetOAuthCode :one
SELECT id, code_hash, user_id, client_id, redirect_uri, code_challenge, expires_at, used_at, grant_id FROM oauth_codes WHERE code_hash = ?1
`

func (q *Queries) GetOAuthCode(ctx context.Context, codeHash string) (OauthCode, error) {
	row := q.db.QueryRowContext(ctx, getOAuthCode, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.GrantID,
	)
	return i, err
}

const getOAuthGrantUser = `-- name: GetOAuthGrantUser :one
SELECT users.id, users.email, users.password_hash, users.display_name, users.is_admin, users.created_at, users.updated_at, users.is_active, users.default_combine_icebox_backlog
FROM oauth_grants
JOIN users ON users.id = oauth_grants.user_id
WHERE oauth_grants.id = ?1
`

func (q *Queries) GetOAuthGrantUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getOAuthGrantUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.DefaultCombineIceboxBacklog,
	)
	return i, err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT oauth_tokens.id, oauth_tokens.grant_id, oauth_tokens.kind, oauth_tokens.token_hash, oauth_tokens.expires_at, oauth_tokens.used_at, oauth_grants.client_id AS grant_client_id
FROM oauth_tokens
JOIN oauth_grants ON oauth_grants.id = oauth_tokens.grant_id
WHERE oauth_tokens.token_hash = ?1
`

type GetOAuthTokenRow struct {
	ID            int64
	GrantID       int64
	Kind          string
	TokenHash     string
	ExpiresAt     int64
	UsedAt        sql.NullInt64
	GrantClientID int64
}

func (q *Queries) GetOAuthToken(ctx context.Context, tokenHash string) (GetOAuthTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getOAuthToken, tokenHash)
	var i GetOAuthTokenRow
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.GrantClientID,
	)
	return i, err
}

const listOAuthGrants = `-- name: ListOAuthGrants :many
SELECT oauth_grants.id, oauth_grants.created_at, oauth_grants.last_used_at, oauth_clients.name AS client_name
FROM oauth_grants
JOIN oauth_clients ON oauth_clients.id = oauth_grants.client_id
WHERE oauth_grants.user_id = ?1
ORDER BY oauth_grants.created_at DESC, oauth_grants.id DESC
`

type ListOAuthGrantsRow struct {
	ID         int64
	CreatedAt  int64
	LastUsedAt sql.NullInt64
	ClientName string
}

func (q *Queries) ListOAuthGrants(ctx context.Context, userID int64) ([]ListOAuthGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOAuthGrantsRow{}
	for rows.Next() {
		var i ListOAuthGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOAuthClient = `-- name: TouchOAuthClient :exec
UPDATE oauth_clients SET last_used_at = ?1 WHERE id = ?2
`

type TouchOAuthClientParams struct {
	Now sql.NullInt64
	ID  int64
}

func (q *Queries) TouchOAuthClient(ctx context.Context, arg TouchOAuthClientParams) error {
	_, err := q.db.ExecContext(ctx, touchOAuthClient, arg.Now, arg.ID)
	return err
}

const touchOAuthGrant = `-- name: TouchOAuthGrant :exec
UPDATE oauth_grants SET last_used_at = ?1 WHERE id = ?2
`

type TouchOAuthGrantParams struct {
	Now sql.NullInt64
	ID  int64
}

func (q *Queries) TouchOAuthGrant(ctx context.Context, arg TouchOAuthGrantParams) error {
	_, err := q.db.ExecContext(ctx, touchOAuthGrant, arg.Now, arg.ID)
	return err
}

const useOAuthCode = `-- name: UseOAuthCode :execrows
UPDATE oauth_codes SET used_at = ?1, grant_id = ?2
WHERE id = ?3 AND used_at IS NULL
`

type UseOAuthCodeParams struct {
	Now     sql.NullInt64
	GrantID sql.NullInt64
	ID      int64
}

func (q *Queries) UseOAuthCode(ctx context.Context, arg UseOAuthCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useOAuthCode, arg.Now, arg.GrantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const useOAuthToken = `-- name: UseOAuthToken :execrows
UPDATE oauth_tokens SET used_at = ?1 WHERE id = ?2 AND used_at IS NULL
`

type UseOAuthTokenParams struct {
	Now sql.NullInt64
	ID  int64
}

func (q *Queries) UseOAuthToken(ctx context.Context, arg UseOAuthTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useOAuthToken, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
