// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planning.sql

package dbgen

import (
	"context"
)

const addStoryBlocker = `-- name: AddStoryBlocker :exec
INSERT INTO story_blockers (story_id, blocker_id) VALUES (?1, ?2)
`

type AddStoryBlockerParams struct {
	StoryID   int64
	BlockerID int64
}

func (q *Queries) AddStoryBlocker(ctx context.Context, arg AddStoryBlockerParams) error {
	_, err := q.db.ExecContext(ctx, addStoryBlocker, arg.StoryID, arg.BlockerID)
	return err
}

const clearStoryBlockers = `-- name: ClearStoryBlockers :exec
DELETE FROM story_blockers WHERE story_id = ?1
`

func (q *Queries) ClearStoryBlockers(ctx context.Context, storyID int64) error {
	_, err := q.db.ExecContext(ctx, clearStoryBlockers, storyID)
	return err
}

const countProjectMembers = `-- name: CountProjectMembers :one
SELECT COUNT(*) FROM project_members WHERE project_id = ?1
`

func (q *Queries) CountProjectMembers(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectMembers, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByProject = `-- name: CountTasksByProject :many
SELECT tasks.story_id, COUNT(*) AS total, COUNT(CASE WHEN tasks.done THEN 1 END) AS done
FROM tasks
JOIN stories ON stories.id = tasks.story_id
WHERE stories.project_id = ?1
GROUP BY tasks.story_id
`

type CountTasksByProjectRow struct {
	StoryID int64
	Total   int64
	Done    int64
}

func (q *Queries) CountTasksByProject(ctx context.Context, projectID int64) ([]CountTasksByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, countTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTasksByProjectRow{}
	for rows.Next() {
		var i CountTasksByProjectRow
		if err := rows.Scan(&i.StoryID, &i.Total, &i.Done); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSavedFilter = `-- name: CreateSavedFilter :one
INSERT INTO saved_filters (user_id, project_id, name, query, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, user_id, project_id, name, "query", created_at
`

type CreateSavedFilterParams struct {
	UserID    int64
	ProjectID int64
	Name      string
	Query     string
	Now       int64
}

func (q *Queries) CreateSavedFilter(ctx context.Context, arg CreateSavedFilterParams) (SavedFilter, error) {
	row := q.db.QueryRowContext(ctx, createSavedFilter,
		arg.UserID,
		arg.ProjectID,
		arg.Name,
		arg.Query,
		arg.Now,
	)
	var i SavedFilter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Name,
		&i.Query,
		&i.CreatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (story_id, description, position, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?4)
RETURNING id, story_id, description, done, position, created_at, updated_at
`

type CreateTaskParams struct {
	StoryID     int64
	Description string
	Position    int64
	Now         int64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.StoryID,
		arg.Description,
		arg.Position,
		arg.Now,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Description,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectMember = `-- name: DeleteProjectMember :exec
DELETE FROM project_members WHERE project_id = ?1 AND user_id = ?2
`

type DeleteProjectMemberParams struct {
	ProjectID int64
	UserID    int64
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const deleteSavedFilter = `-- name: DeleteSavedFilter :execrows
DELETE FROM saved_filters WHERE id = ?1 AND user_id = ?2
`

type DeleteSavedFilterParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSavedFilter(ctx context.Context, arg DeleteSavedFilterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSavedFilter, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT role FROM project_members WHERE project_id = ?1 AND user_id = ?2
`

type GetProjectMemberParams struct {
	ProjectID int64
	UserID    int64
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getTask = `-- name: GetTask :one
SELECT id, story_id, description, done, position, created_at, updated_at FROM tasks WHERE id = ?1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Description,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectBlockers = `-- name: ListProjectBlockers :many
SELECT story_blockers.story_id, story_blockers.blocker_id
FROM story_blockers
JOIN stories ON stories.id = story_blockers.story_id
WHERE stories.project_id = ?1
ORDER BY story_blockers.story_id, story_blockers.blocker_id
`

func (q *Queries) ListProjectBlockers(ctx context.Context, projectID int64) ([]StoryBlocker, error) {
	rows, err := q.db.QueryContext(ctx, listProjectBlockers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoryBlocker{}
	for rows.Next() {
		var i StoryBlocker
		if err := rows.Scan(&i.StoryID, &i.BlockerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT project_members.user_id, project_members.role
FROM project_members
WHERE project_id = ?1
ORDER BY user_id
`

type ListProjectMembersRow struct {
	UserID int64
	Role   string
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID int64) ([]ListProjectMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(&i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT projects.id, projects.name, projects.description, projects.slug, projects.iteration_length_days, projects.iteration_start_weekday, projects.velocity_window, projects.created_at, projects.updated_at FROM projects
WHERE NOT EXISTS (SELECT 1 FROM project_members WHERE project_members.project_id = projects.id)
   OR EXISTS (SELECT 1 FROM project_members WHERE project_members.project_id = projects.id AND project_members.user_id = ?1)
ORDER BY projects.name, projects.id
`

// Projects visible to a user: those with no members at all, or where the user is one.
func (q *Queries) ListProjectsForUser(ctx context.Context, userID int64) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.IterationLengthDays,
			&i.IterationStartWeekday,
			&i.VelocityWindow,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFilters = `-- name: ListSavedFilters :many
SELECT id, user_id, project_id, name, "query", created_at FROM saved_filters
WHERE user_id = ?1 AND project_id = ?2
ORDER BY name
`

type ListSavedFiltersParams struct {
	UserID    int64
	ProjectID int64
}

func (q *Queries) ListSavedFilters(ctx context.Context, arg ListSavedFiltersParams) ([]SavedFilter, error) {
	rows, err := q.db.QueryContext(ctx, listSavedFilters, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedFilter{}
	for rows.Next() {
		var i SavedFilter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Name,
			&i.Query,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoryBlockers = `-- name: ListStoryBlockers :many
SELECT blocker_id FROM story_blockers WHERE story_id = ?1 ORDER BY blocker_id
`

func (q *Queries) ListStoryBlockers(ctx context.Context, storyID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listStoryBlockers, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var blocker_id int64
		if err := rows.Scan(&blocker_id); err != nil {
			return nil, err
		}
		items = append(items, blocker_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, story_id, description, done, position, created_at, updated_at FROM tasks WHERE story_id = ?1 ORDER BY position, id
`

func (q *Queries) ListTasks(ctx context.Context, storyID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.Description,
			&i.Done,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTaskPosition = `-- name: MaxTaskPosition :one
SELECT COALESCE(MAX(position), 0) FROM tasks WHERE story_id = ?1
`

func (q *Queries) MaxTaskPosition(ctx context.Context, storyID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxTaskPosition, storyID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET description = ?1, done = ?2, position = ?3, updated_at = ?4
WHERE id = ?5
RETURNING id, story_id, description, done, position, created_at, updated_at
`

type UpdateTaskParams struct {
	Description string
	Done        bool
	Position    int64
	Now         int64
	ID          int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Description,
		arg.Done,
		arg.Position,
		arg.Now,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Description,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectMember = `-- name: UpsertProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES (?1, ?2, ?3)
ON CONFLICT (project_id, user_id) DO UPDATE SET role = excluded.role
`

type UpsertProjectMemberParams struct {
	ProjectID int64
	UserID    int64
	Role      string
}

func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}
