// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbgen

import (
	"context"
	"database/sql"
)

const clearNonFeatureEstimates = `-- name: ClearNonFeatureEstimates :execrows
UPDATE stories
SET estimate = NULL, updated_at = ?1
WHERE project_id = ?2 AND type <> 'feature' AND estimate IS NOT NULL
`

type ClearNonFeatureEstimatesParams struct {
	Now       int64
	ProjectID int64
}

// Turning bug and chore points off drops the points they already have, so
// the board and velocity never see points the project does not allow.
func (q *Queries) ClearNonFeatureEstimates(ctx context.Context, arg ClearNonFeatureEstimatesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearNonFeatureEstimates, arg.Now, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, slug, iteration_length_days, iteration_start_weekday,
                      velocity_window, estimate_bugs_and_chores, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7,
        ?8, ?8)
RETURNING id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at, archived_at, estimate_bugs_and_chores
`

type CreateProjectParams struct {
	Name                  string
	Description           string
	Slug                  string
	IterationLengthDays   int64
	IterationStartWeekday int64
	VelocityWindow        int64
	EstimateBugsAndChores bool
	Now                   int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.IterationLengthDays,
		arg.IterationStartWeekday,
		arg.VelocityWindow,
		arg.EstimateBugsAndChores,
		arg.Now,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.IterationLengthDays,
		&i.IterationStartWeekday,
		&i.VelocityWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.EstimateBugsAndChores,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at, archived_at, estimate_bugs_and_chores FROM projects WHERE id = ?1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.IterationLengthDays,
		&i.IterationStartWeekday,
		&i.VelocityWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.EstimateBugsAndChores,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at, archived_at, estimate_bugs_and_chores FROM projects WHERE slug = ?1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.IterationLengthDays,
		&i.IterationStartWeekday,
		&i.VelocityWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.EstimateBugsAndChores,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at, archived_at, estimate_bugs_and_chores FROM projects ORDER BY name, id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.IterationLengthDays,
			&i.IterationStartWeekday,
			&i.VelocityWindow,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.EstimateBugsAndChores,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectArchived = `-- name: SetProjectArchived :one
UPDATE projects
SET archived_at = ?1,
    updated_at = ?2
WHERE id = ?3
RETURNING id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at, archived_at, estimate_bugs_and_chores
`

type SetProjectArchivedParams struct {
	ArchivedAt sql.NullInt64
	Now        int64
	ID         int64
}

func (q *Queries) SetProjectArchived(ctx context.Context, arg SetProjectArchivedParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, setProjectArchived, arg.ArchivedAt, arg.Now, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.IterationLengthDays,
		&i.IterationStartWeekday,
		&i.VelocityWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.EstimateBugsAndChores,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = ?1,
    description = ?2,
    iteration_length_days = ?3,
    iteration_start_weekday = ?4,
    velocity_window = ?5,
    estimate_bugs_and_chores = ?6,
    updated_at = ?7
WHERE id = ?8
RETURNING id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at, archived_at, estimate_bugs_and_chores
`

type UpdateProjectParams struct {
	Name                  string
	Description           string
	IterationLengthDays   int64
	IterationStartWeekday int64
	VelocityWindow        int64
	EstimateBugsAndChores bool
	Now                   int64
	ID                    int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.IterationLengthDays,
		arg.IterationStartWeekday,
		arg.VelocityWindow,
		arg.EstimateBugsAndChores,
		arg.Now,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.IterationLengthDays,
		&i.IterationStartWeekday,
		&i.VelocityWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.EstimateBugsAndChores,
	)
	return i, err
}
