// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbgen

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, slug, iteration_length_days, iteration_start_weekday,
                      velocity_window, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7, ?7)
RETURNING id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at
`

type CreateProjectParams struct {
	Name                  string
	Description           string
	Slug                  string
	IterationLengthDays   int64
	IterationStartWeekday int64
	VelocityWindow        int64
	Now                   int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.IterationLengthDays,
		arg.IterationStartWeekday,
		arg.VelocityWindow,
		arg.Now,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.IterationLengthDays,
		&i.IterationStartWeekday,
		&i.VelocityWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at FROM projects WHERE id = ?1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.IterationLengthDays,
		&i.IterationStartWeekday,
		&i.VelocityWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at FROM projects WHERE slug = ?1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.IterationLengthDays,
		&i.IterationStartWeekday,
		&i.VelocityWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at FROM projects ORDER BY name, id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.IterationLengthDays,
			&i.IterationStartWeekday,
			&i.VelocityWindow,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = ?1,
    description = ?2,
    iteration_length_days = ?3,
    iteration_start_weekday = ?4,
    velocity_window = ?5,
    updated_at = ?6
WHERE id = ?7
RETURNING id, name, description, slug, iteration_length_days, iteration_start_weekday, velocity_window, created_at, updated_at
`

type UpdateProjectParams struct {
	Name                  string
	Description           string
	IterationLengthDays   int64
	IterationStartWeekday int64
	VelocityWindow        int64
	Now                   int64
	ID                    int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.IterationLengthDays,
		arg.IterationStartWeekday,
		arg.VelocityWindow,
		arg.Now,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.IterationLengthDays,
		&i.IterationStartWeekday,
		&i.VelocityWindow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
