// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stories.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
)

const countCommentsByProject = `-- name: CountCommentsByProject :many
SELECT comments.story_id, COUNT(*) AS total
FROM comments
JOIN stories ON stories.id = comments.story_id
WHERE stories.project_id = ?1
GROUP BY comments.story_id
`

type CountCommentsByProjectRow struct {
	StoryID int64
	Total   int64
}

func (q *Queries) CountCommentsByProject(ctx context.Context, projectID int64) ([]CountCommentsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, countCommentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCommentsByProjectRow{}
	for rows.Next() {
		var i CountCommentsByProjectRow
		if err := rows.Scan(&i.StoryID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (story_id, user_id, body, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?4)
RETURNING id, story_id, user_id, body, created_at, updated_at
`

type CreateCommentParams struct {
	StoryID int64
	UserID  int64
	Body    string
	Now     int64
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.StoryID,
		arg.UserID,
		arg.Body,
		arg.Now,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (project_id, title, description, type, state, estimate, position,
                     requester_id, owner_id, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?7, ?8, ?9,
        ?10, ?10)
RETURNING id, project_id, title, description, type, state, estimate, position, requester_id, owner_id, created_at, updated_at, accepted_at
`

type CreateStoryParams struct {
	ProjectID   int64
	Title       string
	Description string
	Type        string
	State       string
	Estimate    sql.NullInt64
	Position    int64
	RequesterID int64
	OwnerID     sql.NullInt64
	Now         int64
}

func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error) {
	row := q.db.QueryRowContext(ctx, createStory,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.State,
		arg.Estimate,
		arg.Position,
		arg.RequesterID,
		arg.OwnerID,
		arg.Now,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.State,
		&i.Estimate,
		&i.Position,
		&i.RequesterID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const deleteStory = `-- name: DeleteStory :exec
DELETE FROM stories WHERE id = ?1
`

func (q *Queries) DeleteStory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStory, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, story_id, user_id, body, created_at, updated_at FROM comments WHERE id = ?1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStory = `-- name: GetStory :one
SELECT id, project_id, title, description, type, state, estimate, position, requester_id, owner_id, created_at, updated_at, accepted_at FROM stories WHERE id = ?1
`

func (q *Queries) GetStory(ctx context.Context, id int64) (Story, error) {
	row := q.db.QueryRowContext(ctx, getStory, id)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.State,
		&i.Estimate,
		&i.Position,
		&i.RequesterID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const listAcceptedStories = `-- name: ListAcceptedStories :many
SELECT id, project_id, title, description, type, state, estimate, position, requester_id, owner_id, created_at, updated_at, accepted_at FROM stories
WHERE project_id = ?1
  AND accepted_at IS NOT NULL
  AND accepted_at >= ?2
  AND accepted_at < ?3
ORDER BY accepted_at, id
`

type ListAcceptedStoriesParams struct {
	ProjectID      int64
	AcceptedFrom   sql.NullInt64
	AcceptedBefore sql.NullInt64
}

func (q *Queries) ListAcceptedStories(ctx context.Context, arg ListAcceptedStoriesParams) ([]Story, error) {
	rows, err := q.db.QueryContext(ctx, listAcceptedStories, arg.ProjectID, arg.AcceptedFrom, arg.AcceptedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.State,
			&i.Estimate,
			&i.Position,
			&i.RequesterID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveStories = `-- name: ListActiveStories :many
SELECT id, project_id, title, description, type, state, estimate, position, requester_id, owner_id, created_at, updated_at, accepted_at FROM stories
WHERE project_id = ?1
  AND (accepted_at IS NULL OR accepted_at >= ?2)
ORDER BY position, id
`

type ListActiveStoriesParams struct {
	ProjectID     int64
	AcceptedSince sql.NullInt64
}

// Every story that is still "live": everything not accepted, plus stories
// accepted at or after the given instant (the start of the current iteration).
func (q *Queries) ListActiveStories(ctx context.Context, arg ListActiveStoriesParams) ([]Story, error) {
	rows, err := q.db.QueryContext(ctx, listActiveStories, arg.ProjectID, arg.AcceptedSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.State,
			&i.Estimate,
			&i.Position,
			&i.RequesterID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT id, story_id, user_id, body, created_at, updated_at FROM comments WHERE story_id = ?1 ORDER BY id
`

func (q *Queries) ListComments(ctx context.Context, storyID int64) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionPositions = `-- name: ListSectionPositions :many
SELECT id, position FROM stories
WHERE project_id = ?1
  AND state IN (/*SLICE:states*/?)
ORDER BY position, id
`

type ListSectionPositionsParams struct {
	ProjectID int64
	States    []string
}

type ListSectionPositionsRow struct {
	ID       int64
	Position int64
}

// Ordered ids/positions for one ordering scope. The caller passes the states
// that make up the section (see story.Section).
func (q *Queries) ListSectionPositions(ctx context.Context, arg ListSectionPositionsParams) ([]ListSectionPositionsRow, error) {
	query := listSectionPositions
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProjectID)
	if len(arg.States) > 0 {
		for _, v := range arg.States {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(arg.States))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSectionPositionsRow{}
	for rows.Next() {
		var i ListSectionPositionsRow
		if err := rows.Scan(&i.ID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchStories = `-- name: SearchStories :many
SELECT id, project_id, title, description, type, state, estimate, position, requester_id, owner_id, created_at, updated_at, accepted_at FROM stories
WHERE project_id = ?1
  AND LOWER(title || ' ' || description) LIKE ?2
ORDER BY position, id
`

type SearchStoriesParams struct {
	ProjectID int64
	Pattern   string
}

// The pattern ('%term%', lower-cased) is built in Go; LOWER() keeps behaviour
// identical between SQLite and PostgreSQL. sqlc's SQLite parser has no ESCAPE
// support, so % and _ typed by a user simply act as wildcards.
func (q *Queries) SearchStories(ctx context.Context, arg SearchStoriesParams) ([]Story, error) {
	rows, err := q.db.QueryContext(ctx, searchStories, arg.ProjectID, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.State,
			&i.Estimate,
			&i.Position,
			&i.RequesterID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStoryPosition = `-- name: SetStoryPosition :exec
UPDATE stories SET position = ?1 WHERE id = ?2
`

type SetStoryPositionParams struct {
	Position int64
	ID       int64
}

func (q *Queries) SetStoryPosition(ctx context.Context, arg SetStoryPositionParams) error {
	_, err := q.db.ExecContext(ctx, setStoryPosition, arg.Position, arg.ID)
	return err
}

const updateStory = `-- name: UpdateStory :one
UPDATE stories
SET title = ?1,
    description = ?2,
    type = ?3,
    state = ?4,
    estimate = ?5,
    position = ?6,
    requester_id = ?7,
    owner_id = ?8,
    accepted_at = ?9,
    updated_at = ?10
WHERE id = ?11
RETURNING id, project_id, title, description, type, state, estimate, position, requester_id, owner_id, created_at, updated_at, accepted_at
`

type UpdateStoryParams struct {
	Title       string
	Description string
	Type        string
	State       string
	Estimate    sql.NullInt64
	Position    int64
	RequesterID int64
	OwnerID     sql.NullInt64
	AcceptedAt  sql.NullInt64
	Now         int64
	ID          int64
}

func (q *Queries) UpdateStory(ctx context.Context, arg UpdateStoryParams) (Story, error) {
	row := q.db.QueryRowContext(ctx, updateStory,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.State,
		arg.Estimate,
		arg.Position,
		arg.RequesterID,
		arg.OwnerID,
		arg.AcceptedAt,
		arg.Now,
		arg.ID,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.State,
		&i.Estimate,
		&i.Position,
		&i.RequesterID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
	)
	return i, err
}
