// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, user_id, name, token_hash, created_at, last_used_at, expires_at
`

type CreateAPITokenParams struct {
	UserID    int64
	Name      string
	TokenHash string
	CreatedAt int64
	ExpiresAt sql.NullInt64
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM api_tokens WHERE id = ?1 AND user_id = ?2
`

type DeleteAPITokenParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserAPITokens = `-- name: DeleteUserAPITokens :exec
DELETE FROM api_tokens WHERE user_id = ?1
`

func (q *Queries) DeleteUserAPITokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserAPITokens, userID)
	return err
}

const getAPITokenUser = `-- name: GetAPITokenUser :one
SELECT api_tokens.id AS token_id, api_tokens.last_used_at, users.id, users.email, users.password_hash, users.display_name, users.is_admin, users.created_at, users.updated_at, users.is_active
FROM api_tokens
JOIN users ON users.id = api_tokens.user_id
WHERE api_tokens.token_hash = ?1
  AND (api_tokens.expires_at IS NULL OR api_tokens.expires_at > ?2)
  AND users.is_active
`

type GetAPITokenUserParams struct {
	TokenHash string
	Now       sql.NullInt64
}

type GetAPITokenUserRow struct {
	TokenID    int64
	LastUsedAt sql.NullInt64
	User       User
}

func (q *Queries) GetAPITokenUser(ctx context.Context, arg GetAPITokenUserParams) (GetAPITokenUserRow, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenUser, arg.TokenHash, arg.Now)
	var i GetAPITokenUserRow
	err := row.Scan(
		&i.TokenID,
		&i.LastUsedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.DisplayName,
		&i.User.IsAdmin,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.IsActive,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, name, token_hash, created_at, last_used_at, expires_at FROM api_tokens WHERE user_id = ?1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPITokens(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = ?1 WHERE id = ?2
`

type TouchAPITokenParams struct {
	Now sql.NullInt64
	ID  int64
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.Now, arg.ID)
	return err
}
